export const TableVehiclesMock = {
  columns: [
    { key: 'store', label: 'Loja' },
    { key: 'plate', label: 'Placa' },
    { key: 'brand', label: 'Marca' },
    { key: 'year', label: 'Ano' },
    { key: 'color', label: 'Cor' },
    { key: 'renavam', label: 'Renavam' },
    { key: 'document', label: 'CPF/CNPJ' },
    { key: 'actions', label: 'Ações' },
  ],

  vehicles: [
    {
      store: 'Loja Adamantina',
      cliente: 'João Silva',
      plate: 'ABC-1234',
      brand: 'Toyota',
      year: 2020,
      vin: 'teste',
      model: 'palio',
      color: 'Prata',
      renavam: '12345678901',
      insuranceClaimNumber: '12345',
      document: '123.456.789-00',
    },
    {
      store: 'Loja São Caetano do Sul',
      cliente: 'Maria Oliveira',
      plate: 'XYZ-9876',
      brand: 'Honda',
      year: 2018,
      model: 'palio',
      vin: 'teste',
      color: 'Preto',
      renavam: '98765432100',
      insuranceClaimNumber: '67890',
      document: '12.345.678/0001-90',
    },
    {
      store: 'Loja Caieiras',
      cliente: 'Pedro Santos',
      plate: 'DEF-5678',
      brand: 'Ford',
      model: 'palio',
      year: 2022,
      vin: 'teste',
      color: 'Branco',
      renavam: '45678912345',
      insuranceClaimNumber: '54321',
      document: '987.654.321-00',
    },
  ],
};
